services:
  # ------------------- Backend (FastAPI + Uvicorn)
  - type: web
    name: backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    autoDeploy: true
    plan: free

  # ------------------- Frontend (React Build + Serve)
  - type: web
    name: frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s build -l $PORT
    autoDeploy: true
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: https://backend.onrender.com   # 👈 replace after first backend deploy
